# Generated by Django 5.2.5 on 2025-09-04 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Task'},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('title',)},
        ),
        migrations.AlterModelTable(
            name='task',
            table='task_manager_task',
        ),
    ]
