# Generated by Django 5.2.5 on 2025-09-04 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_tasks', '0002_alter_task_options_alter_task_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category'},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name',)},
        ),
        migrations.AlterModelTable(
            name='category',
            table='task_manager_category',
        ),
    ]
