# Generated by Django 5.2.5 on 2025-09-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_tasks', '0003_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Категория выполнения (срочность)', max_length=30, verbose_name='Название категории'),
        ),
    ]
