# Generated by Django 5.2.5 on 2025-09-28 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_tasks', '0005_alter_category_name_alter_task_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set(),
        ),
    ]
